#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentation.Modelado
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASEMU")]
	public partial class AsumeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public AsumeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ProyectoAsemu"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AsumeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AsumeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AsumeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AsumeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CrearUsuarios")]
		public int SP_CrearUsuarios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedulaAsociado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string correoElectronico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string contrasenna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string sal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEstadoDatos)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedulaAsociado, correoElectronico, idRol, contrasenna, sal, idEstadoDatos);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuarios;
		
		private System.Nullable<int> _cedulaAsociado;
		
		private string _correoElectronico;
		
		private System.Nullable<int> _idRol;
		
		private string _contrasenna;
		
		private string _salt;
		
		private System.Nullable<int> _idEstadoDatos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuariosChanging(int value);
    partial void OnidUsuariosChanged();
    partial void OncedulaAsociadoChanging(System.Nullable<int> value);
    partial void OncedulaAsociadoChanged();
    partial void OncorreoElectronicoChanging(string value);
    partial void OncorreoElectronicoChanged();
    partial void OnidRolChanging(System.Nullable<int> value);
    partial void OnidRolChanged();
    partial void OncontrasennaChanging(string value);
    partial void OncontrasennaChanged();
    partial void OnsaltChanging(string value);
    partial void OnsaltChanged();
    partial void OnidEstadoDatosChanging(System.Nullable<int> value);
    partial void OnidEstadoDatosChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarios", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuarios
		{
			get
			{
				return this._idUsuarios;
			}
			set
			{
				if ((this._idUsuarios != value))
				{
					this.OnidUsuariosChanging(value);
					this.SendPropertyChanging();
					this._idUsuarios = value;
					this.SendPropertyChanged("idUsuarios");
					this.OnidUsuariosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaAsociado", DbType="Int")]
		public System.Nullable<int> cedulaAsociado
		{
			get
			{
				return this._cedulaAsociado;
			}
			set
			{
				if ((this._cedulaAsociado != value))
				{
					this.OncedulaAsociadoChanging(value);
					this.SendPropertyChanging();
					this._cedulaAsociado = value;
					this.SendPropertyChanged("cedulaAsociado");
					this.OncedulaAsociadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoElectronico", DbType="VarChar(100)")]
		public string correoElectronico
		{
			get
			{
				return this._correoElectronico;
			}
			set
			{
				if ((this._correoElectronico != value))
				{
					this.OncorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._correoElectronico = value;
					this.SendPropertyChanged("correoElectronico");
					this.OncorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRol", DbType="Int")]
		public System.Nullable<int> idRol
		{
			get
			{
				return this._idRol;
			}
			set
			{
				if ((this._idRol != value))
				{
					this.OnidRolChanging(value);
					this.SendPropertyChanging();
					this._idRol = value;
					this.SendPropertyChanged("idRol");
					this.OnidRolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasenna", DbType="VarChar(150)")]
		public string contrasenna
		{
			get
			{
				return this._contrasenna;
			}
			set
			{
				if ((this._contrasenna != value))
				{
					this.OncontrasennaChanging(value);
					this.SendPropertyChanging();
					this._contrasenna = value;
					this.SendPropertyChanged("contrasenna");
					this.OncontrasennaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salt", DbType="VarChar(150)")]
		public string salt
		{
			get
			{
				return this._salt;
			}
			set
			{
				if ((this._salt != value))
				{
					this.OnsaltChanging(value);
					this.SendPropertyChanging();
					this._salt = value;
					this.SendPropertyChanged("salt");
					this.OnsaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEstadoDatos", DbType="Int")]
		public System.Nullable<int> idEstadoDatos
		{
			get
			{
				return this._idEstadoDatos;
			}
			set
			{
				if ((this._idEstadoDatos != value))
				{
					this.OnidEstadoDatosChanging(value);
					this.SendPropertyChanging();
					this._idEstadoDatos = value;
					this.SendPropertyChanged("idEstadoDatos");
					this.OnidEstadoDatosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
